Exercice complet 1 — Iris Dataset (NumPy)

Étape 1 — Télécharger le dataset

In [4]:
import numpy as np

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

data = np.genfromtxt(url, delimiter=',', dtype=str)
data = data[~np.all(data == '', axis=1)]

Étape 2 — Explorer le dataset

In [5]:
print("Shape du dataset :", data.shape)
print("5 premières lignes :\n", data[:5])


Shape du dataset : (150, 5)
5 premières lignes :
 [['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']]


Étape 3 — Séparer features et labels

In [7]:
X = data[:,:-1].astype(float)
y_str  = data[:, -1]
classes = np.unique(y_str)
y = np.array([np.where(classes == label)[0][0] for label in y_str])
print("X_shape : ", X.shape)
print("y shape : ", y.shape)

X_shape :  (150, 4)
y shape :  (150,)


Étape 4 — Normaliser les features

In [8]:
mean = X.mean(axis=0)
std = X.std(axis=0)
X_norm = (X - mean) / std
print(X_norm)

[[-9.00681170e-01  1.03205722e+00 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00 -1.24957601e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.38535265e+00  3.37848329e-01 -1.39813811e+00 -1.31297673e+00]
 [-1.50652052e+00  1.06445364e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.02184904e+00  1.26346019e+00 -1.34127240e+00 -1.31297673e+00]
 [-5.37177559e-01  1.95766909e+00 -1.17067529e+00 -1.05003079e+00]
 [-1.50652052e+00  8.00654259e-01 -1.34127240e+00 -1.18150376e+00]
 [-1.02184904e+00  8.00654259e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.74885626e+00 -3.56360566e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00  1.06445364e-01 -1.28440670e+00 -1.44444970e+00]
 [-5.37177559e-01  1.49486315e+00 -1.28440670e+00 -1.31297673e+00]
 [-1.26418478e+00  8.00654259e-01 -1.22754100e+00 -1.31297673e+00]
 [-1.26418478e+00 -1.24957601e-01 -1.34127240e+00 -1.44444970e+00]
 [-1.87002413e+00 -1.24957601e-01 -1.51186952e+00 -1.44444970e+00]
 [-5.25060772e-02  2.18907205e+00 -1.45500381e+00 -1.31297673e

Étape 5 — Créer mini-batchs

Essentiel pour utiliser moins de memoire

In [9]:
batch_size = 16
for i in range(0, X_norm.shape[0], batch_size):
    X_batch = X_norm[i:i+batch_size]
    y_batch = y[i:i+batch_size]
    print("Batch X shape :", X_batch.shape, "Batch y shape :", y_batch.shape)

Batch X shape : (16, 4) Batch y shape : (16,)
Batch X shape : (16, 4) Batch y shape : (16,)
Batch X shape : (16, 4) Batch y shape : (16,)
Batch X shape : (16, 4) Batch y shape : (16,)
Batch X shape : (16, 4) Batch y shape : (16,)
Batch X shape : (16, 4) Batch y shape : (16,)
Batch X shape : (16, 4) Batch y shape : (16,)
Batch X shape : (16, 4) Batch y shape : (16,)
Batch X shape : (16, 4) Batch y shape : (16,)
Batch X shape : (6, 4) Batch y shape : (6,)
