In [2]:
import numpy as np

Extraire les éléments d’indice 5 à 14

Extraire un élément sur deux

In [3]:
A = np.arange(20)
A[5:15]
A[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

extraire la sous-matrice centrale (2×2)

extraire la première colonne

In [4]:
M = np.arange(1, 17).reshape(4, 4)
M[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

garder seulement les scores ≥ 10

remplacer les scores < 5 par 0

In [5]:
scores = np.array([8, 14, 3, 17, 10, 6])
score1 = scores[scores >= 10]
scores[scores < 5] =0
scores

array([ 8, 14,  0, 17, 10,  6])

In [6]:
a = np.arange(20)
print(a)
a[5:2:-1]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([5, 4, 3])

In [7]:
"a[start:stop:step]"
img = np.arange(36).reshape(6,6)
img[1:-1, 1:-1]

array([[ 7,  8,  9, 10],
       [13, 14, 15, 16],
       [19, 20, 21, 22],
       [25, 26, 27, 28]])

Extraire tous les multiples de 3 par slicing uniquement

Inverser le tableau

Extraire les 7 derniers éléments dans l’ordre inverse

In [8]:
a = np.arange(1, 31)
print(a[2::3])
print(a[::-1])
print(a[:-7:-1])

[ 3  6  9 12 15 18 21 24 27 30]
[30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7
  6  5  4  3  2  1]
[30 29 28 27 26 25]


In [9]:
a.reshape(3, -1) 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [10]:
X = np.arange(1_000_000).reshape(1_000_000, 1)
Y = np.zeros_like(X)

Y = X  ** 2
Y

array([[           0],
       [           1],
       [           4],
       ...,
       [999994000009],
       [999996000004],
       [999998000001]], shape=(1000000, 1))

🔥 Exercice 1 — Vectorisation simple

Élever au carré chaque élément

Prendre racine

Multiplier par 2 + 1

In [11]:
a = np.arange(1, 11)
print(a**2)
print(np.sqrt(a))

[  1   4   9  16  25  36  49  64  81 100]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


*Exercice 1* — Dataset tabulaire

Fusionner X et y

Shuffle

Split train/test 60/40

Extraire X_train, y_train, X_test, y_test

In [26]:
X = np.arange(20).reshape(5,4)
y = np.array([0,1,0,1,0])

data = np.hstack([X, y.reshape(-1, 1)])
np.random.shuffle(data)
n_train = int(len(data)* 0.6)
X_train = data[:n_train:]
X_test = data[n_train::]
X_test

array([[ 4,  5,  6,  7,  1],
       [16, 17, 18, 19,  0]])

In [ ]:
X = np.arange(1000000)
Y = np.zeros_like(X)

for i in range(X.shape[0]):
    Y[i] = X[i]**2


KeyboardInterrupt: 

In [ ]:
Y = X**2

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets

ModuleNotFoundError: No module named 'sklearn'